[project]
name = "data-ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.0.0",
    "psycopg2-binary>=2.9.0",
    "pyspark>=3.5.0",
    "python-dotenv>=1.0.0",
    "sqlalchemy>=2.0.0",
]
